CREATE TABLE "credentials" (
	id uuid NOT NULL CONSTRAINT credentials_pk PRIMARY KEY,
	password CHARACTER VARYING(255) NOT NULL,
	"deletedAt" CHARACTER VARYING(255),
	"createdAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	"updatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

ALTER TABLE "credentials" OWNER TO "dbUser";
